<?php

namespace OC\PlatformBundle\Repository;

/**
 * apiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class apiRepository extends \Doctrine\ORM\EntityRepository
{
}
