<?php

namespace OC\PlatformBundle\Repository;

/**
 * page_detailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class page_detailsRepository extends \Doctrine\ORM\EntityRepository
{
}
